spring:
  datasource:
    url: "jdbc:sqlserver://masterdb.dev.qiaofangyun.com:1433;DatabaseName=qfcommon"
    username: sa
    password: 9itImGqc3dk7IPt8FG23VQ==
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    initialSize: 10
    minIdle: 2
    maxActive: 100
    maxWait: 5000
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 5000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 200
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    logAbandoned: true
    proxyFilters: stat-filter
    slowSqlMillis: 2000
    logSlowSql: true
    mergeSql: false
    loginDruidUsername: admin
    loginDruidPassword: password2
    dbType: sqlserver
    logViolation: true
    throwException: true 
lts:
  tasktracker:
    cluster-name: qf_cluster
    registry-address: zookeeper://zoo1:2181,zoo2:2181,zoo3:2181
    node-group: CommonServiceTaskTracker
    configs:
      job:
        fail:
          store: mapdb
