swagger:
  enabled: true

ignoreToken:
  enabled: false

zuul:
  routes:
    hbsharewebbff-route:
      path: /api/hbsharewebbff/**
      url: http://hbsharewebbff:14002
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 50000
    connect-timeout-millis: 50000
  add-host-header: true
  
spring:
  defaultDatasource:
    url: "jdbc:mysql://localhost:3306/hb_share_dev?useSSL=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true"
    username: root
    password: HI8m4mZQc5s=
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 100Mb
ignore:
  url: /hbsharewebbff