spring: 
  defaultDatasource:
    url: "jdbc:sqlserver://192.168.10.107:1433;DatabaseName=hb_organization"
    username: h_organization
    password: T51poeU8hiOZGIxJmVKM4KmawywcbLCI
lts:
  tasktracker:
    cluster-name: qf_cluster
    registry-address: zookeeper://zoo1:2181,zoo2:2181,zoo3:2181
    node-group: CommonServiceTaskTracker
    configs:
      job:
        fail:
          store: mapdb
singleLogin: true
defaultCity:
    uuid: 8F499FAB-A408-4E8F-8E50-C1E8BBB8E2D0
    name: 上海
wx: 
    appId: wx553d4b09800ee9e9
    appSecret: f7b889c5fad3599a6d88ad06d70fbd36
    token: qiaofang
    aesKey: f82PVzQsKG5d8en3DwnZ8VVEoGInkmsWz3X3HsreEqe
    mchId: 
    apiKey: 
