spring: 
  defaultDatasource:
    url: "jdbc:sqlserver://192.168.10.107:1433;DatabaseName=hb_property"
    username: h_property
    password: Pbe2lKJNYdb9J1WCSu0aakzbcFyln81p
lts:
  tasktracker:
    cluster-name: qf_cluster
    registry-address: zookeeper://zoo1:2181,zoo2:2181,zoo3:2181
    node-group: CommonServiceTaskTracker
    configs:
      job:
        fail:
          store: mapdb
          
