swagger:
 enabled: true

zuul:
  add-host-header: true
  
defaultLogin:
  userName: admin
  password: qiaofang123
  
spring:
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 100Mb
