spring: 
  defaultDatasource:
    url: "jdbc:sqlserver://192.168.16.52:1433;DatabaseName=hb_organization"
    username: sa
    password: 9itImGqc3dk7IPt8FG23VQ==
lts:
  tasktracker:
    cluster-name: qf_cluster
    registry-address: zookeeper://zoo1:2181,zoo2:2181,zoo3:2181
    node-group: CommonServiceTaskTracker
    configs:
      job:
        fail:
          store: mapdb
singleLogin: false
defaultCity:
    uuid: 8F499FAB-A408-4E8F-8E50-C1E8BBB8E2D0
    name: 上海
wx: 
    appId: wxd658ceb1a1792d0e
    appSecret: 2e5b66393b84e48a3930808df329f95c
    token: qiaofang
    aesKey: f82PVzQsKG5d8en3DwnZ8VVEoGInkmsWz3X3HsreEqe
    mchId: 
    apiKey: 
