spring: 
  defaultDatasource:
    url: "jdbc:sqlserver://192.168.16.158:1433;DatabaseName=hb_share_uat"
    username: sa
    password: 9itImGqc3dk7IPt8FG23VQ==
lts:
  tasktracker:
    cluster-name: qf_cluster
    registry-address: zookeeper://zoo1:2181,zoo2:2181,zoo3:2181
    node-group: CommonServiceTaskTracker
    configs:
      job:
        fail:
          store: mapdb
qf:
  fyapi:
    appid: 1111
    appkey: e327bad4-6320-479c-b93e-21ea152d8925
    broker-property-url: http://fyapi.uat.qiaofangyun.com/fyapi/v1/fyapi/property/getBrokerCirclePropertyInfo?propertyUuid={propertyUuid}
    broker-employee-url: http://fyapi.uat.qiaofangyun.com/fyapi/v1/fyapi/user/getBrokerCircleEmployee?employeeUuid={employeeUuid}
    publish-property-url: http://fyapi.uat.qiaofangyun.com/fyapi/v1/fyapi/hbProperty/publishProperty
    unshelve-property-url: http://fyapi.uat.qiaofangyun.com/fyapi/v1/fyapi/hbProperty/unShelveProperty